# Generated by Django 4.2 on 2025-07-12 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_carbrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.carbrand'),
        ),
    ]
