# Generated by Django 4.2 on 2025-07-12 19:42

import car.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_car_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=car.models.brand_thumbnail_upload_path),
        ),
    ]
