# Generated by Django 4.2 on 2025-07-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_carbrand_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbooking',
            name='special_requests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
