# Generated by Django 4.2 on 2025-07-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_roombooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='map_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
