# Generated by Django 4.2 on 2025-07-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_hotel_map_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='bed_type',
            field=models.CharField(choices=[('king', 'King Bed'), ('queen', 'Queen Bed'), ('twin', 'Twin Beds'), ('double', 'Double Bed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('twin', 'Twin Room'), ('triple', 'Triple Room'), ('quad', 'Quad Room'), ('queen', 'Queen Room'), ('king', 'King Room'), ('standard', 'Standard Room'), ('deluxe', 'Deluxe Room'), ('superior', 'Superior Room'), ('executive', 'Executive Room'), ('junior_suite', 'Junior Suite'), ('suite', 'Suite'), ('penthouse', 'Penthouse Suite'), ('family', 'Family Room'), ('accessible', 'Accessible Room'), ('studio', 'Studio'), ('connecting', 'Connecting Rooms'), ('presidential', 'Presidential Suite'), ('executive_suite', 'Executive Suite')], max_length=50),
        ),
    ]
