# Generated by Django 4.2 on 2025-07-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_normalize_room_type_bed_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='province',
            field=models.CharField(choices=[('Kigali City', 'Kigali City'), ('Northern', 'Northern'), ('Southern', 'Southern'), ('Eastern', 'Eastern'), ('Western', 'Western')], max_length=100),
        ),
    ]
