# Generated by Django 4.2 on 2025-07-12 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaneBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('origin', models.CharField(help_text='City or Airport of Departure', max_length=255)),
                ('destination', models.CharField(help_text='City or Airport of Arrival', max_length=255)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('trip_type', models.CharField(choices=[('one_way', 'One Way'), ('round_trip', 'Round Trip')], default='one_way', max_length=20)),
                ('travel_class', models.CharField(choices=[('economy', 'Economy'), ('premium_economy', 'Premium Economy'), ('business', 'Business'), ('first_class', 'First Class')], default='economy', max_length=20)),
                ('num_adults', models.PositiveIntegerField(default=1)),
                ('num_children', models.PositiveIntegerField(default=0)),
                ('num_infants', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='Any special requests or additional info')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plane_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plane Booking',
                'verbose_name_plural': 'Plane Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
